// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.companyname.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
