// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.companyname.grpc;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 responseCode = 1;</code>
   */
  int getResponseCode();

  /**
   * <code>string responseMessage = 2;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
